// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PureSound.Data;

#nullable disable

namespace PureSound.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240401064136_Mig3")]
    partial class Mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "91dba846-9346-4180-926b-822a512114a8",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "59becd7f-9fa3-4daf-99f6-f52f5568dcc6",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "389e650a-775f-4d7b-a9ac-30cfd960fa37",
                            RoleId = "91dba846-9346-4180-926b-822a512114a8"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PureSound.Data.Account.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("FavGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("~/img/profilePhoto.png");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FavGenreId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "389e650a-775f-4d7b-a9ac-30cfd960fa37",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30337ff6-9bfd-42dc-a608-c0e82675dccd",
                            Email = "etaleksander411@gmail.com",
                            EmailConfirmed = false,
                            FavGenreId = new Guid("48d67181-5732-47a0-892b-6577fc688e00"),
                            LockoutEnabled = false,
                            NormalizedEmail = "ETALEKSANDER411@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEJPpNmMc9YLHeCQnjSeGO0Uc50/S8otMVLKsyhrhTN/Iz9uoZH3N4D7e6SR/hGdlVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13ed8cd2-3eda-4a6d-9276-738db82a7511",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("PureSound.Data.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("RegionId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("PureSound.Data.Entities.ArtistTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TrackId");

                    b.ToTable("ArtistTrack");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecc0c732-51bf-45d0-a646-785e578b92ed"),
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = new Guid("c13f4755-8c79-46be-aa27-7b1505eab3ac"),
                            Name = "BREAKING"
                        },
                        new
                        {
                            Id = new Guid("4bb7ea19-d5e7-425e-975f-d1ff8c821505"),
                            Name = "New production"
                        },
                        new
                        {
                            Id = new Guid("5a404d01-59b0-467f-aa0c-b784965f925c"),
                            Name = "Rising stars"
                        });
                });

            modelBuilder.Entity("PureSound.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PureSound.Data.Entities.FavouriteArtists", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("UserId1");

                    b.ToTable("FavouriteArtists");
                });

            modelBuilder.Entity("PureSound.Data.Entities.FavouriteTracks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId1");

                    b.ToTable("FavouriteTracks");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("adbdd114-7d5f-49c6-883c-4134428f491b"),
                            Name = "Rap"
                        },
                        new
                        {
                            Id = new Guid("1b99263a-f107-46ca-9130-1671a8b8e674"),
                            Name = "Drill"
                        },
                        new
                        {
                            Id = new Guid("80961a64-8c18-4cc8-9476-d4d5637c6466"),
                            Name = "Raeggeton"
                        },
                        new
                        {
                            Id = new Guid("0cc47a8b-fa7b-4a2f-8976-dbfd317408c6"),
                            Name = "House"
                        },
                        new
                        {
                            Id = new Guid("510fbafe-4d46-43f3-b9ee-d4e3273ee160"),
                            Name = "R&B"
                        },
                        new
                        {
                            Id = new Guid("864665ff-ed41-4f80-9fb9-ae7ff997f550"),
                            Name = "Techno"
                        },
                        new
                        {
                            Id = new Guid("20b699af-cdf9-4d6c-83f7-7273d52403ae"),
                            Name = "Phonk"
                        },
                        new
                        {
                            Id = new Guid("48d67181-5732-47a0-892b-6577fc688e00"),
                            Name = "None"
                        });
                });

            modelBuilder.Entity("PureSound.Data.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18ff037f-9216-4144-acd8-34afbc7b0ec4"),
                            Name = "West Coast (NORTH AMERICA)"
                        },
                        new
                        {
                            Id = new Guid("2dcafb5c-498e-4e0e-907c-00ea009c01a4"),
                            Name = "East Coast (NORTH AMERICA)"
                        },
                        new
                        {
                            Id = new Guid("8d13d374-998d-4394-ac14-2e7d416791ec"),
                            Name = "South America"
                        },
                        new
                        {
                            Id = new Guid("c8b05d04-4d24-4967-9d3b-499209f67358"),
                            Name = "Latin America"
                        },
                        new
                        {
                            Id = new Guid("e9f403cc-e3de-4864-842b-62b3b90968db"),
                            Name = "Africa"
                        },
                        new
                        {
                            Id = new Guid("63faaca2-7b5c-463a-b76b-a784b4ed36e2"),
                            Name = "Middle East (ASIA)"
                        },
                        new
                        {
                            Id = new Guid("112673bc-f145-4bcd-8329-1b10b7fe1084"),
                            Name = "West Europe"
                        },
                        new
                        {
                            Id = new Guid("c8f91217-3925-420a-8350-a3eb74e2ceec"),
                            Name = "East Europe"
                        },
                        new
                        {
                            Id = new Guid("95f8df2d-e7fb-4aa5-8bf9-0f8b8ee7587e"),
                            Name = "Balkans (EUROPE)"
                        },
                        new
                        {
                            Id = new Guid("dd6d8c55-12bd-411d-8707-afa7ce8f252c"),
                            Name = "Oceania"
                        },
                        new
                        {
                            Id = new Guid("290f1082-0449-49cd-86d1-0059a99be0ec"),
                            Name = "East Asia"
                        },
                        new
                        {
                            Id = new Guid("a1f4c1b9-3670-4be8-bdee-8334ec7165f4"),
                            Name = "Middle Asia"
                        },
                        new
                        {
                            Id = new Guid("5b225ec7-fb5d-4228-acb6-d9a14be0bbe1"),
                            Name = "West Asia"
                        },
                        new
                        {
                            Id = new Guid("d07cd5fe-c2e6-46a7-87a0-2d427ea9d05a"),
                            Name = "None"
                        });
                });

            modelBuilder.Entity("PureSound.Data.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lyrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<string>("YouTubeURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PureSound.Data.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PureSound.Data.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureSound.Data.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PureSound.Data.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PureSound.Data.Account.User", b =>
                {
                    b.HasOne("PureSound.Data.Entities.Genre", "FavGenre")
                        .WithMany("Users")
                        .HasForeignKey("FavGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavGenre");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Article", b =>
                {
                    b.HasOne("PureSound.Data.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Artist", b =>
                {
                    b.HasOne("PureSound.Data.Entities.Genre", "Genre")
                        .WithMany("Artists")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureSound.Data.Entities.Region", "Region")
                        .WithMany("Artists")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PureSound.Data.Entities.ArtistTrack", b =>
                {
                    b.HasOne("PureSound.Data.Entities.Artist", "Artist")
                        .WithMany("ArtistTrack")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureSound.Data.Entities.Track", "Track")
                        .WithMany("ArtistTrack")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Comment", b =>
                {
                    b.HasOne("PureSound.Data.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureSound.Data.Account.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureSound.Data.Entities.FavouriteArtists", b =>
                {
                    b.HasOne("PureSound.Data.Entities.Artist", "Artist")
                        .WithMany("FavoriteArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureSound.Data.Account.User", "User")
                        .WithMany("FavouriteArtists")
                        .HasForeignKey("UserId1");

                    b.Navigation("Artist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureSound.Data.Entities.FavouriteTracks", b =>
                {
                    b.HasOne("PureSound.Data.Entities.Track", "Track")
                        .WithMany("FavoriteTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureSound.Data.Account.User", "User")
                        .WithMany("FavouriteTracks")
                        .HasForeignKey("UserId1");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Track", b =>
                {
                    b.HasOne("PureSound.Data.Entities.Genre", "Genre")
                        .WithMany("Tracks")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("PureSound.Data.Account.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavouriteArtists");

                    b.Navigation("FavouriteTracks");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Artist", b =>
                {
                    b.Navigation("ArtistTrack");

                    b.Navigation("FavoriteArtists");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Genre", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Tracks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Region", b =>
                {
                    b.Navigation("Artists");
                });

            modelBuilder.Entity("PureSound.Data.Entities.Track", b =>
                {
                    b.Navigation("ArtistTrack");

                    b.Navigation("FavoriteTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
